//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeZoner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeZoner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timezones.csv
        ///Country Code;Country Name;GMT Offset
        ///BF;Burkina Faso;UTC
        ///GM;Gambia;UTC
        ///GH;Ghana;UTC
        ///GL;Greenland;UTC
        ///GL;Greenland;UTC
        ///GN;Guinea;UTC
        ///GW;Guinea-Bissau;UTC
        ///IS;Iceland;UTC
        ///CI;Ivory Coast;UTC
        ///LR;Liberia;UTC
        ///ML;Mali;UTC
        ///MR;Mauritania;UTC
        ///PT;Portugal;UTC
        ///SH;Saint Helena;UTC
        ///SN;Senegal;UTC
        ///SL;Sierra Leone;UTC
        ///TG;Togo;UTC
        ///CV;Cape Verde;UTC -01:00
        ///BR;Brazil;UTC -02:00
        ///GL;Greenland;UTC -02:00
        ///PM;Saint Pierre and Miquelon;UTC -02:00
        ///GS;South Georgia and the South Sandwich Islands;UT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string time_zones {
            get {
                return ResourceManager.GetString("time_zones", resourceCulture);
            }
        }
    }
}
